<p style="font-family: Arial; font-size:3em;color:black;"> Lab W1 </p>

Students name in this Group:
Daniyar
Purvi
Rishabh
Vrinda


In [19]:
# importing numpy
import numpy as np

In [20]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
arr = np.array([1,2,3,5,0])
print(arr)
zero_element = False
for x in arr:
    if x==0:
        zero_element = True

if zero_element:
    print("Array has an element which is Zero")
else:
    print("Array has all non zero elements")


[1 2 3 5 0]
Array has an element which is Zero


Note:as the procedure is being repeated im replicating the same using functions

In [21]:
def check_if_element_is_zero(arr1):
    zero_element = False
    for x in arr1:
        if x==0:
            zero_element = True
    if zero_element:
        print("Array has an element which is Zero")
    else:
        print("Array has all non zero elements")


In [22]:
arr = np.array([1,2,3,5,0])
print(arr)
check_if_element_is_zero(arr)

[1 2 3 5 0]
Array has an element which is Zero


In [23]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.
arr1 = np.array([3,-1,3,7,2])
print(arr1)
zero_element = False
for x in arr1:
    if x==0:
        zero_element = True

if zero_element:
    print("Array has an element which is Zero")
else:
    print("Array has all non zero elements")
        

[ 3 -1  3  7  2]
Array has all non zero elements


In [24]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.
arr3 = np.array([0,0,0,0])
print(arr)
check_if_element_is_zero(arr)

[1 2 3 5 0]
Array has an element which is Zero


In [25]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.
arr3 = np.array([56,-2,7])
print(arr3)
arr3.nbytes


[56 -2  7]


24

In [26]:
import numpy as np

In [27]:
# Create a numpy array with 10 zeros and print the array.
arr4 = np.zeros(10)
print(arr4)
# Create a numpy array with 6 ones and print the array.
arr5 = np.ones(6)
print(arr5)
# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
arr6 = np.ones(12)*3
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [28]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
import numpy as np
arr7 = np.arange(8,21,2)
print(arr7)

# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method


[ 8 10 12 14 16 18 20]


In [29]:
# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?
# mean is decreasing as the random elements are increasing.
# standard deviation is increasing as the random elements are increasing.

In [30]:
#Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
import numpy as np
my_std = 0.5
my_mean = 2
x = my_std * np.random.randn(100) + my_mean
print("Average:",x.mean())
print("Min",min(x))
print("Max",max(x))
print("Standard deviation",x.std())


Average: 2.0104754987243236
Min 0.943910257519798
Max 3.2242607217904533
Standard deviation 0.5388917311791603


In [31]:
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
import numpy as np
my_std = 0.5
my_mean = 2
x = my_std * np.random.randn(1000) + my_mean
print("Average:",x.mean())
print("Min",min(x))
print("Max",max(x))
print("Standard deviation",x.std())


Average: 1.9942219417774587
Min 0.5514834808072382
Max 3.89505651085185
Standard deviation 0.514752879026346


In [32]:
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
import numpy as np
my_std = 0.5
my_mean = 2
x = my_std * np.random.randn(1000000) + my_mean
print("Average:",x.mean())
print("Min",min(x))
print("Max",max(x))
print("Standard deviation",x.std())

Average: 2.0000022586161124
Min -0.4344578484637309
Max 4.439381719664495
Standard deviation 0.5002195643782247
